language: dart
os: linux
matrix:
  include:
    - stage: Flutter Test
    - before_script:
        - "cd dengue_app"
      addons:
        apt:
          packages:
            - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache
