name: dengue_app
description: Dengue Stop community application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: Raleway
     fonts:
       - asset: assets/fonts/Raleway-Regular.ttf
       - asset: assets/fonts/Raleway-Italic.ttf
         style: italic
       - asset: assets/fonts/Raleway-Thin.ttf
         style: italic
         weight: 200
       - asset: assets/fonts/Raleway-ExtraLight.ttf
         style: italic
         weight: 300
       - asset: assets/fonts/Raleway-Light.ttf
         style: italic
         weight: 400
       - asset: assets/fonts/Raleway-Medium.ttf
         style: italic
         weight: 500
       - asset: assets/fonts/Raleway-SemiBold.ttf
         style: italic
         weight: 600
       - asset: assets/fonts/Raleway-Bold.ttf
         style: italic
         weight: 700
       - asset: assets/fonts/Raleway-ExtraBold.ttf
         style: italic
         weight: 800
       - asset: assets/fonts/Raleway-Black.ttf
         style: italic
         weight: 900
       - asset: assets/fonts/Raleway-ThinItalic.ttf
         weight: 200
       - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
         weight: 300
       - asset: assets/fonts/Raleway-LightItalic.ttf
         weight: 400
       - asset: assets/fonts/Raleway-MediumItalic.ttf
         weight: 500
       - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
         weight: 600
       - asset: assets/fonts/Raleway-BoldItalic.ttf
         weight: 700
       - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
         weight: 800
       - asset: assets/fonts/Raleway-BlackItalic.ttf
         weight: 900
