"""empty message

Revision ID: 45f19eb703da
Revises: 48b8d064086e
Create Date: 2020-06-21 02:44:50.999271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f19eb703da'
down_revision = '48b8d064086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('alert_type', sa.String(length=45), nullable=False),
    sa.Column('subject', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('venue', sa.String(length=45), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_long', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('coordinator_name', sa.String(length=45), nullable=False),
    sa.Column('coordinator_contact', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('org_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=45), nullable=False),
    sa.Column('district', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_status')
    op.drop_table('org_unit')
    op.drop_table('event_status')
    op.drop_table('event')
    op.drop_table('alert')
    # ### end Alembic commands ###
