"""empty message

Revision ID: 48b8d064086e
Revises: b274c32ad000
Create Date: 2020-06-21 02:43:23.970812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b8d064086e'
down_revision = 'b274c32ad000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('salt', sa.String(length=45), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
