"""empty message

Revision ID: 642f401fa199
Revises: 
Create Date: 2020-06-21 02:37:12.061020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642f401fa199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=45), nullable=False),
    sa.Column('district', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('patient_name', sa.String(length=45), nullable=False),
    sa.Column('patient_gender', sa.String(length=1), nullable=False),
    sa.Column('patient_dob', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('reported_time', sa.DateTime(), nullable=True),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_status_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('nic_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('salt', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('incident')
    # ### end Alembic commands ###
