"""empty message

Revision ID: 6a3b0250510f
Revises: 7a11382d2cbd
Create Date: 2020-07-25 01:24:44.334857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a3b0250510f'
down_revision = '7a11382d2cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('salt', mysql.VARCHAR(length=45), nullable=False))
    # ### end Alembic commands ###
