"""Add foreign key constraints

Revision ID: 744eb5e08247
Revises: d486e396846b
Create Date: 2020-06-22 00:19:24.442642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744eb5e08247'
down_revision = 'd486e396846b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin', 'org_unit', ['org_id'], ['id'])
    op.create_foreign_key(None, 'alert', 'org_unit', ['org_id'], ['id'])
    op.create_foreign_key(None, 'alert', 'admin', ['creator_id'], ['id'])
    op.add_column('event', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'admin', ['created_by'], ['id'])
    op.create_foreign_key(None, 'event', 'event_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'event', 'org_unit', ['org_id'], ['id'])
    op.create_foreign_key(None, 'incident', 'admin', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'incident', 'org_unit', ['org_id'], ['id'])
    op.create_foreign_key(None, 'incident', 'patient_status', ['patient_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'created_by')
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    # ### end Alembic commands ###
