"""Add district province foreign key

Revision ID: 8d1421257ded
Revises: b38c88db7b1e
Create Date: 2020-06-22 02:55:58.706506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1421257ded'
down_revision = 'b38c88db7b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'district', 'province', ['province_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'district', type_='foreignkey')
    # ### end Alembic commands ###
