"""empty message

Revision ID: b274c32ad000
Revises: 642f401fa199
Create Date: 2020-06-21 02:38:46.703132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b274c32ad000'
down_revision = '642f401fa199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident', 'reported_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident', 'reported_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
