"""empty message

Revision ID: d486e396846b
Revises: 45f19eb703da
Create Date: 2020-06-21 23:37:32.823652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd486e396846b'
down_revision = '45f19eb703da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'incident', 'user', ['reported_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    # ### end Alembic commands ###
